name: contact_tracing
description: A contact tracing app to help find contaminated people with a virus.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
 # sdk: ">=2.7.0 <3.0.0"
 # flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2 #cupertino_icons: ^1.0.3
  path_provider: ^2.0.2
  #flutter_restart: ^0.0.3
  csv: ^5.0.0
  #permission_handler: ^8.1.4+2
  tuple: ^2.0.0
  latlong2: ^0.8.0
  #positioned_tap_detector_2: ^1.0.0
  transparent_image: ^2.0.0
  async: ^2.6.1
  flutter_image: ^4.1.0
  vector_math: ^2.1.0
  proj4dart: ^2.0.0
  meta: ^1.3.0
  collection: ^1.15.0
  flutter_map: ^0.13.1
  location: ^4.3.0
  geolocator: ^7.4.0
  ftpconnect: ^1.0.0
  #flutter_osm_plugin: ^0.7.5
  #cron: ^0.3.0
  move_to_background: ^1.0.2
  shared_preferences: ^2.0.7
  #workmanager: ^0.4.0
  #flutter_local_notifications: ^8.1.1+1
  map_markers: ^0.1.0
  flutter_background_service: ^0.1.5
  #services: ^0.0.1
  http: ^0.13.3
  flutter_native_timezone: ^2.0.0
  device_info: ^2.0.2
  rxdart: ^0.27.1
  test: ^1.16.8 #1.9.0 #1.17.11
  mockito: ^5.0.15 #5.0.14 #4.1.4
  pedantic: ^1.11.1
  speech_bubble: ^0.0.9
  splashscreen: ^1.3.5
 # animated_dialog_box: ^0.0.2
  cool_alert: ^1.1.0
  flutter_holo_date_picker: ^0.3.4+1
  flutter_country_picker: ^0.1.6
  intl_phone_number_input: ^0.7.0+2
  grouped_buttons: ^1.0.4
  # firebase_messaging: ^10.0.1
  # firebase_core: ^1.6.0  
  dots_indicator: ^2.0.0
 # country_list_pick:
 # country_codes: ^2.0.1
  country_code: ^1.0.0
  geocoder: ^0.2.1
  csc_picker: ^0.2.6
  firebase_core: "^1.10.0"
  firebase_messaging: ^11.2.0
  flutter_local_notifications: ^9.1.4
  #http: ^0.13.0
  firebase_auth: ^3.3.0
  firebase_analytics: ^8.3.4
  cloud_firestore: ^3.1.1
  firebase_database: ^9.0.3
  flutter_app_badger: ^1.3.0
  badges: ^2.0.2




dev_dependencies:
  flutter_test:
    sdk: flutter
  

flutter:
  uses-material-design: true

