name: contact_tracing
description: A contact tracing app to help find contaminated people with a virus.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  path_provider: ^2.0.2
  latlong2: ^0.8.0
  async: ^2.6.1
  flutter_map: ^0.14.0
  geolocator: ^8.0.1
  ftpconnect: ^1.0.0
  shared_preferences: ^2.0.7
  flutter_background_service: ^0.1.5
  http: ^0.13.3
  device_info: ^2.0.2
  flutter_holo_date_picker: ^1.0.1+2
  intl_phone_number_input: ^0.7.0+2
  grouped_buttons: ^1.0.4
  dots_indicator: ^2.0.0
  geocoder: ^0.2.1  
  flutter_app_badger: ^1.3.0
  badges: ^2.0.2
  otp_text_field: ^1.1.1
  provider: ^6.0.1
  firebase_core: "^1.10.0"
  firebase_messaging: ^11.2.0
  flutter_local_notifications: ^9.1.4
  firebase_auth: ^3.3.0
  firebase_analytics: ^9.0.4
  cloud_firestore: ^3.1.1
  firebase_database: ^9.0.3
  connectivity: ^3.0.6

  

  
flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/icon/icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "lib/assets/icon/ic_launcher/1024.png"

flutter_native_splash:
  android: true
  ios: true
  color: "#dedede"
  image: "lib/assets/icon/icon.png"
  color_dark: "#696969"
  image_dark: "lib/assets/icon/icon.png"

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^1.3.2
  flutter_test:
    sdk: flutter
  

flutter:
  uses-material-design: true

